/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fmod.hpp>
#include <unistd.h>
/* Header for class com_rainy_livechangevoice_VoiceUtil */
/* 利用 javah -classpath . -jni com.rainy.livechangevoice.VoiceUtil
*/
#ifndef _Included_com_rainy_livechangevoice_VoiceUtil
#define _Included_com_rainy_livechangevoice_VoiceUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rainy_livechangevoice_VoiceUtil_MODE_YUANSHENG
#define com_rainy_livechangevoice_VoiceUtil_MODE_YUANSHENG 0L
#undef com_rainy_livechangevoice_VoiceUtil_MODE_LUOLI
#define com_rainy_livechangevoice_VoiceUtil_MODE_LUOLI 1L
#undef com_rainy_livechangevoice_VoiceUtil_MODE_DASHU
#define com_rainy_livechangevoice_VoiceUtil_MODE_DASHU 2L
#undef com_rainy_livechangevoice_VoiceUtil_MODE_GAOGUAI
#define com_rainy_livechangevoice_VoiceUtil_MODE_GAOGUAI 3L
#undef com_rainy_livechangevoice_VoiceUtil_MODE_KONGLING
#define com_rainy_livechangevoice_VoiceUtil_MODE_KONGLING 4L
#undef com_rainy_livechangevoice_VoiceUtil_MODE_JINGSONG
#define com_rainy_livechangevoice_VoiceUtil_MODE_JINGSONG 5L
/*
 * Class:     com_rainy_livechangevoice_VoiceUtil
 * Method:    voiceChange
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_rainy_livechangevoice_VoiceUtil_voiceChange
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
